version: '3.3'

services:
  db:
    container_name: "moudle_db"
    build: 
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3307:3306"
    expose: 
      # Opens port 3306 on the container
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "Modules"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  web:
    container_name: frontend
    build: 
      context: ./frontend
    restart: always
    ports:
      - "8170:8170"
  api:
    container_name: "moudle_api"
    build: 
      context: .
      dockerfile: api.Dockerfile
    networks:
      - default
    ports:
      - "8171:8171"
    expose:
      - "8171"
    depends_on:
      - db
    volumes:
      - .:/app/
networks:
  default:
    driver: bridge
volumes:
  mysql_data:      